main:
  "crontab: 0 * * * *":
    - name: Run
      runner:
        cpus: 2
      docker:
        image: docker.cnb.cool/oxzk.co/code-server:latest
      imports: https://cnb.cool/oxzk.co/env/-/blob/main/vector.json
      stages:
        - name: Set up Python venv
          script: |
            if ! command -v pip >/dev/null 2>&1; then
              . ~/.venv/bin/activate
            fi
            python cli.py tester

        - name: Install dependencies
          script: |
            if command -v pip >/dev/null 2>&1; then
              pip install -r requirements.txt
            fi


# main:
#   push:
#     - runner:
#         cpus: 2
#       docker:
#         image: docker.cnb.cool/oxzk.co/code-server:latest
#       imports: https://cnb.cool/oxzk.co/env/-/blob/main/v2ray.json
#       stages:
#         - name: python
#           script: |
#             ls -la
#             nohup v2ray -c /root/.cnb/v2ray-config.json >/dev/null 2>&1 &

$:
  vscode:
    - runner:
        cpus: 4
        # tags: cnb:arch:amd64:gpu
      docker:
        image: docker.cnb.cool/oxzk.co/code-server:latest
      services:
        - vscode
        - docker
      stages:
        - name: cnb-init
          script: |
            bash /root/.cnb/cnb-init.sh
      endStages:
        - name: cnb-end
          script: |
            bash /root/.cnb/cnb-destory.sh